version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: npm start
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  db:
    image: postgres
    volumes:
      - chatdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
volumes:
  chatdb:
    external: true
